### ISSUE TITLE
No composer package available

### ISSUE THREAD

**Issue by jamespsterling** [pagerange/session#1]
```
  [InvalidArgumentException]
  Could not find package pagerange/session at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by pagerange** [comment]
Package is not yet available on Packagist, so cannot be installed with a simple `composer require pagerange/session`.   However, it can still be installed with composer by adding this repo to your composer.json file and running `composer install`.  README has been updated to reflect this

``` json

{

 "repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/pagerange/session.git"
  }
 ],
 "require": {
  "pagerange/session": "@alpha"
 }

}

```
